---
- name: Stop Classic VSI
  uri:
    url: "{{ sl_api_base }}/SoftLayer_Virtual_Guest/{{ vsi_id }}/powerOff.json"
    method: GET
    user: "{{ classic_username }}"
    password: "{{ classic_api_key }}"
    force_basic_auth: yes
    status_code: 200
    return_content: yes
  register: result

- name: Debug result
  debug:
    msg: "{{ result }}"