---
- name: Generate random suffix for bucket
  set_fact:
    cos_bucket_name: "{{ cos_bucket_prefix }}{{ lookup('password', '/dev/null length=6 chars=ascii_letters') | lower }}"

- name: Create COS bucket
  amazon.aws.s3_bucket:
    name: "{{ cos_bucket_name }}"
    state: present
    region: "{{ lookup('env','COS_REGION') }}"
    endpoint_url: "{{ lookup('env','COS_ENDPOINT') }}"
    aws_access_key: "{{ lookup('env','COS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env','COS_SECRET_ACCESS_KEY') }}"
  register: bucket_result

- name: Ensure folder prefix exists in bucket
  amazon.aws.s3_object:
    bucket: "{{ cos_bucket_name }}"
    object: "{{ folder_prefix }}"
    mode: create
    endpoint_url: "{{ lookup('env','COS_ENDPOINT') }}"
    aws_access_key: "{{ lookup('env','COS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env','COS_SECRET_ACCESS_KEY') }}"
  when: bucket_result.changed
